# Global config, e.g. references
threads: 8
data_dir: "test_data"
output_dir: "test_results"
reference_fasta: "test_data/hbb_locus_grch38.fa"
reference_gtf: "test_data/hbb_test.gtf"
fwd_primer: "test_data/forward_primers.fasta"
rev_primer: "test_data/reverse_primers.fasta"
clinvar_variants: "test_data/clinvar_variants.tsv"
MANE_transcripts: "test_data/MANE_select_transcripts.tsv"

cases:
  - name: example_HBB_case
    case_sample: barcode02_case
    case_control: barcode01_control
    chrom: "chr11"
    start_pos: 5400 #Start position of the gene -100bp to increase visualisation window
    end_pos: 7150 #End position of the gene +100bp to increase visualisation window
    gene: "HBB"
    variant_name: ["rs334"] #Example format ["c.1234A>G", "c.111+222A>G"]
    variant_pos: [7003] #Genomic position of variant for visualising on the output figures, cannot be a range
    prop_threshold: 0.05 #This allows for manual resetting of the proportion threshold for complex transcript profiles e.g. 0.001
    mane_id: "ENST00000335295.4" #Or the most highly expressed transcript ID for the tissue utilised, for comparison
